### ISSUE TITLE
Add support for Unicode & Other Text Characters/Symbols (Multi-Lingual Support)

### ISSUE THREAD

**Issue by JannesStroehlein** [stream-pi/essential-actions#12] opened 2021-03-02 08:57 UTC
Hello,

I wanted to add a TextBlock action to paste "СУКА БЛЯТЬ" (I'm not Russian so I have to Google every time to get the Cyrillic Version of cyka blyat). As I pressed to Icon on my RasPi I got this error message:
![image](https://user-images.githubusercontent.com/48127946/109613967-34d6b680-7b32-11eb-92b3-08ac3538f411.png)

Also my Windows Key stop working and caps got activated permanently. The PRINT key didn't work too. I had to kill the StreamPi server with the task manager.

**Comment by rnayabed** [comment] 2021-03-07 04:55
This is not possible currently. The java Robot class has no provision to type unicode characters. This may be resolved in the future.

**Comment by TOGLK** [comment] 2021-03-10 11:05
Please update the title to be more relevant to the source of the issue.

The issue is caused by a lack of Unicode Support within Stream-Pi, so with that in mind the "Title" for this issue should read as follows:

[Cross-Platform] [Feature Request] Add support for Unicode & Other Text Characters/Symbols (Multi-Lingual Support)

**Comment by rnayabed** [comment] 2021-03-10 12:40
> The issue is caused by a lack of Unicode Support within Stream-Pi, so with that in mind the "Title" for this issue should read as follows:

It's not due to lack of support of unicode within Stream-Pi. You can have stuff like display names, etc set with unicode characters. Its a java side issue since their robot class doesnt support this. In the future if some other method instead of robot is used, this may be solved.

**Comment by rnayabed** [comment] 2021-12-24 19:26
https://github.com/stream-pi/essential-actions/commit/c34723b9b0f2a881c4350a8a49bad2d5d0214cc1 should fix this.

**Closed by rnayabed** 2021-12-24 19:26 UTC
Labels: New Feature, Community Submission, Hotkey Action
